import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
import { XR8Scripts } from 'react-8thwall-aframe';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <XR8Scripts xr8ApiKey={process.env.XR8_API_KEY} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
